---
apiVersion: v1
kind: Service
metadata:
  name: obs-bingo
  namespace: obs-bingo
  labels:
    app: obs-bingo
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: obs-bingo
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-bingo
  namespace: obs-bingo
  labels:
    app: obs-bingo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obs-bingo
  template:
    metadata:
      labels:
        app: obs-bingo
    spec:
      containers:
      - name: obs-bingo
        image: ghcr.io/dilaz/obs-bingo:9276c2cc93ad35ce0588370d82c7fff4ff2885ac
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: github-container-registry
